<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-9M4ATQT" failures="3" tests="5" name="Test" time="0.072" errors="0" timestamp="07 Sep 2019 06:19:30 GMT">
  <testcase classname="org.test.login.TestNG.TestNGGroup" name="logic1" time="0.018">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.test.login.TestNG.TestNGGroup.logic1(TestNGGroup.java:9)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- logic1 -->
  <testcase classname="org.test.login.TestNG.TestNGGroup" name="logic2" time="0.003">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.test.login.TestNG.TestNGGroup.logic2(TestNGGroup.java:15)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- logic2 -->
  <testcase classname="org.test.login.TestNG.TestNGGroup" name="logic3" time="0.001"/>
  <testcase classname="org.test.login.TestNG.TestNGGroup" name="logic4" time="0.002">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.test.login.TestNG.TestNGGroup.logic4(TestNGGroup.java:27)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- logic4 -->
  <testcase classname="org.test.login.TestNG.TestNGGroup" name="logic5" time="0.001"/>
</testsuite> <!-- Test -->
